# Generated by Django 4.1.4 on 2023-01-07 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cost_control_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='date_check',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='checks',
            name='photo_check',
            field=models.FileField(blank=True, null=True, upload_to='uploads/<django.db.models.query_utils.DeferredAttribute object at 0x000001B7FF02F250>/'),
        ),
        migrations.AlterField(
            model_name='checks',
            name='text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
