# Generated by Django 4.1.4 on 2023-01-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_control_project', '0002_alter_checks_date_check_alter_checks_photo_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='photo_check',
            field=models.FileField(blank=True, null=True, upload_to='cost_control_project/<django.db.models.query_utils.DeferredAttribute object at 0x00000154E096F3A0>/'),
        ),
    ]
