# Generated by Django 4.1.4 on 2023-01-12 10:33

import cost_control_project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_control_project', '0003_alter_checks_photo_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='photo_check',
            field=models.FileField(blank=True, null=True, upload_to=cost_control_project.models.user_directory_path),
        ),
    ]
