# Generated by Django 4.1.4 on 2023-02-26 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cost_control_project', '0004_alter_checks_photo_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_purchase', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='checks',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cost_control_project.categorypurchase'),
        ),
    ]
