# Generated by Django 4.1.4 on 2023-02-26 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cost_control_project', '0005_categorypurchase_checks_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypurchase',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
